
name: ci
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          if [ -d scripts ]; then shellcheck scripts/*.sh || true; fi
